// <auto-generated />
using System;
using AdvEcommerceProj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdvEcommerceProj.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20181207165838_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdvEcommerceProj.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("category");
                });

            modelBuilder.Entity("AdvEcommerceProj.Models.CreditCardInfocs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("creditcardnumber");

                    b.Property<DateTime>("expdate");

                    b.Property<int>("orderid");

                    b.HasKey("id");

                    b.HasIndex("orderid");

                    b.ToTable("creditcardinfo");
                });

            modelBuilder.Entity("AdvEcommerceProj.Models.Customers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<int>("age");

                    b.Property<string>("name");

                    b.Property<string>("phone");

                    b.HasKey("id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("AdvEcommerceProj.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("customerid");

                    b.Property<DateTime>("order_date");

                    b.Property<int>("quantity");

                    b.HasKey("id");

                    b.HasIndex("customerid");

                    b.ToTable("order");
                });

            modelBuilder.Entity("AdvEcommerceProj.Models.Products", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Supplierid");

                    b.Property<int?>("categoryid");

                    b.Property<int>("catid");

                    b.Property<string>("name");

                    b.Property<int>("price");

                    b.Property<int>("sid");

                    b.Property<int>("stock");

                    b.HasKey("ID");

                    b.HasIndex("Supplierid");

                    b.HasIndex("categoryid");

                    b.ToTable("products");
                });

            modelBuilder.Entity("AdvEcommerceProj.Models.Supplier", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address");

                    b.Property<string>("name");

                    b.Property<string>("phone");

                    b.HasKey("id");

                    b.ToTable("psupplier");
                });

            modelBuilder.Entity("AdvEcommerceProj.Models.CreditCardInfocs", b =>
                {
                    b.HasOne("AdvEcommerceProj.Models.Order", "order")
                        .WithMany()
                        .HasForeignKey("orderid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AdvEcommerceProj.Models.Order", b =>
                {
                    b.HasOne("AdvEcommerceProj.Models.Customers", "customer")
                        .WithMany("order")
                        .HasForeignKey("customerid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AdvEcommerceProj.Models.Products", b =>
                {
                    b.HasOne("AdvEcommerceProj.Models.Supplier")
                        .WithMany("products")
                        .HasForeignKey("Supplierid");

                    b.HasOne("AdvEcommerceProj.Models.Category", "category")
                        .WithMany("product")
                        .HasForeignKey("categoryid");
                });
#pragma warning restore 612, 618
        }
    }
}
